import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';process.env.DATABASE_PATH=path.resolve('data/test-watchable.db');process.env.BILLING_PROVIDER='mock';try{fs.unlinkSync(process.env.DATABASE_PATH)}catch{}
const {createUser,getUserAuthByEmail,verifyPassword}=await import('../src/auth.js');const {createCheckout,getSubscription,listCommissionSummary}=await import('../src/billing.js');const {getDb,closeDb}=await import('../src/db.js');const {seedDemo}=await import('../src/seed.js');const {listChannels,listVod,createPlaybackSession,scheduleRecording,listRecordings}=await import('../src/content.js');const {ingestPackage}=await import('../src/ingest.js');const {discover,tracks,createParty,joinParty,listEvents,shortForm,franchisePortfolio,creatorDashboard}=await import('../src/ecosystem.js');seedDemo();
test('account creation hashes password and authenticates',async()=>{const u=await createUser({email:'customer@example.com',password:'very-secure-password',displayName:'Customer'});assert.equal(u.email,'customer@example.com');const a=getUserAuthByEmail('CUSTOMER@example.com');assert.ok(a.password_hash.includes(':'));assert.equal(await verifyPassword('very-secure-password',a.password_hash),true)});
test('mock subscription activates $75 plan and awards recurring-sales ledger entry',async()=>{const u=getUserAuthByEmail('customer@example.com'),c=await createCheckout({user:u,repCode:'FOUNDING20'});assert.equal(c.activated,true);assert.equal(getSubscription(u.id).commission_rate,.20);const rep=getDb().prepare('SELECT * FROM reps WHERE code=?').get('FOUNDING20');assert.equal(listCommissionSummary(rep.id).commission_cents,1500)});
test('subscriber can play and DVR rights-cleared content',()=>{const u=getUserAuthByEmail('customer@example.com'),ch=listChannels()[0],s=createPlaybackSession({userId:u.id,assetType:'channel',assetId:ch.id});assert.ok(s.token);const p=getDb().prepare('SELECT * FROM programs WHERE channel_id=? LIMIT 1').get(ch.id);assert.equal(scheduleRecording(u.id,p.id).status,'scheduled');assert.ok(listRecordings(u.id).length)});
test('content ingestion fails closed without verified rights',()=>assert.throws(()=>ingestPackage({source:{name:'Unverified',adapterType:'LICENSED_LINEAR',status:'active',rightsVerified:false},channels:[]}),/rightsVerified/));
test('verified package is normalized',()=>{const r=ingestPackage({source:{name:'Fixture Supplier',adapterType:'LICENSED_LINEAR',status:'active',rightsVerified:true,config:{contractReference:'TEST'}},channels:[{slug:'fixture-channel',name:'Fixture Channel',category:'Entertainment',playbackUrl:'https://example.invalid/master.m3u8',playbackType:'hls',territories:['US'],dvrAllowed:true}],vod:[{slug:'fixture-vod',title:'Fixture VOD',kind:'movie',playbackUrl:'https://example.invalid/movie.m3u8',playbackType:'hls',territories:['US']}]});assert.equal(r.channelCount,1);assert.equal(r.vodCount,1)});
test('multilingual discovery and accessibility tracks are first-class',()=>{const u=getUserAuthByEmail('customer@example.com'),asset=listVod().find(x=>x.slug==='spanish-premium-demo');const d=discover({userId:u.id,language:'es'});assert.ok(d.vod.length);const t=tracks('vod',asset.id);assert.ok(t.some(x=>x.language==='es'));assert.ok(t.some(x=>x.language==='ko'))});
test('watch parties, events, shorts and franchise rights are operational primitives',()=>{const u=getUserAuthByEmail('customer@example.com'),asset=listVod()[0],p=createParty(u.id,{assetType:'vod',assetId:asset.id});assert.equal(joinParty(u.id,p.joinCode).id,p.id);assert.ok(listEvents().length);assert.ok(shortForm().length);const f=franchisePortfolio()[0];assert.ok(f.rights_count>=9)});
test('creator dashboard exposes transparent economics',()=>{const c=getDb().prepare('SELECT * FROM creators LIMIT 1').get(),d=creatorDashboard(c.id);assert.ok(d.creator);assert.ok(d.revenue.some(x=>x.creator_cents>0))});
test.after(()=>{closeDb();try{fs.unlinkSync(process.env.DATABASE_PATH)}catch{}});
