import { getDb } from './db.js';
import { id, now } from './util.js';

const parse=(v,fallback={})=>{try{return JSON.parse(v||'')}catch{return fallback}};
export function discover({userId,profileId,language,mood,category,limit=24}={}){const db=getDb();const profile=profileId?db.prepare('SELECT * FROM profiles WHERE id=? AND user_id=?').get(profileId,userId):null;const prefs=profile?parse(profile.preferred_languages,[]):[];const lang=language||prefs[0];const kids=profile?.is_kids===1;let vod=db.prepare('SELECT * FROM vod_assets WHERE active=1').all();let channels=db.prepare('SELECT * FROM channels WHERE active=1').all();const score=x=>{const m=parse(x.metadata_json,{});let s=0;if(category&&(x.category===category||m.categories?.includes(category)))s+=6;if(lang&&(m.languages?.includes(lang)||m.subtitleLanguages?.includes(lang)||m.audioLanguages?.includes(lang)))s+=5;if(mood&&m.moods?.includes(mood))s+=3;if(kids&&m.audience==='kids')s+=10;if(kids&&m.audience==='adult')s-=100;return s;};return {channels:channels.map(x=>({...x,score:score(x)})).filter(x=>x.score>-50).sort((a,b)=>b.score-a.score).slice(0,limit),vod:vod.map(x=>({...x,score:score(x)})).filter(x=>x.score>-50).sort((a,b)=>b.score-a.score).slice(0,limit)};}
export function whatsOnNow(){const t=now();return getDb().prepare(`SELECT p.*,c.name channel_name,c.category FROM programs p JOIN channels c ON c.id=p.channel_id WHERE p.starts_at<=? AND p.ends_at>? AND c.active=1 ORDER BY c.name`).all(t,t);}
export function tracks(assetType,assetId){return getDb().prepare('SELECT * FROM media_tracks WHERE asset_type=? AND asset_id=? ORDER BY track_type,is_default DESC,language').all(assetType,assetId);}
export function recordWatch({userId,profileId,assetType,assetId,eventType='progress',positionSeconds=0,metadata={}}){const event={id:id('we'),createdAt:now()};getDb().prepare('INSERT INTO watch_events(id,user_id,profile_id,asset_type,asset_id,event_type,position_seconds,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(event.id,userId,profileId||null,assetType,assetId,eventType,positionSeconds,JSON.stringify(metadata),event.createdAt);return event;}
export function continueWatching(userId,profileId){return getDb().prepare(`SELECT asset_type,asset_id,MAX(created_at) last_seen,MAX(position_seconds) position_seconds FROM watch_events WHERE user_id=? AND (? IS NULL OR profile_id=?) AND event_type IN ('progress','pause','play') GROUP BY asset_type,asset_id ORDER BY last_seen DESC LIMIT 30`).all(userId,profileId||null,profileId||null);}
export function createAlert(userId,b){const a={id:id('alt'),createdAt:now()};getDb().prepare('INSERT INTO alerts(id,user_id,profile_id,asset_type,asset_id,alert_type,status,created_at) VALUES(?,?,?,?,?,?,?,?)').run(a.id,userId,b.profileId||null,b.assetType,b.assetId,b.alertType||'premiere','active',a.createdAt);return a;}
export function createParty(userId,b){const p={id:id('pty'),joinCode:Math.random().toString(36).slice(2,8).toUpperCase(),createdAt:now()};getDb().prepare('INSERT INTO watch_parties(id,host_user_id,asset_type,asset_id,join_code,status,starts_at,created_at) VALUES(?,?,?,?,?,?,?,?)').run(p.id,userId,b.assetType,b.assetId,p.joinCode,b.status||'scheduled',b.startsAt||null,p.createdAt);getDb().prepare('INSERT INTO party_members(party_id,user_id,joined_at) VALUES(?,?,?)').run(p.id,userId,p.createdAt);return p;}
export function joinParty(userId,code){const p=getDb().prepare('SELECT * FROM watch_parties WHERE join_code=?').get(String(code).toUpperCase());if(!p)throw Object.assign(new Error('Watch party not found'),{statusCode:404});getDb().prepare('INSERT OR IGNORE INTO party_members(party_id,user_id,joined_at) VALUES(?,?,?)').run(p.id,userId,now());return p;}
export function listEvents(){return getDb().prepare("SELECT * FROM live_events WHERE status!='cancelled' ORDER BY starts_at").all();}
export function eventChat(userId,eventId,message){if(!String(message||'').trim())throw Object.assign(new Error('Message required'),{statusCode:400});const e={id:id('chat'),createdAt:now()};getDb().prepare('INSERT INTO event_chat(id,event_id,user_id,message,status,created_at) VALUES(?,?,?,?,?,?)').run(e.id,eventId,userId,String(message).trim().slice(0,500),'visible',e.createdAt);return e;}
export function redeemGift(userId,code){const db=getDb();const g=db.prepare("SELECT * FROM gift_codes WHERE code=? AND status='active'").get(String(code).trim().toUpperCase());if(!g)throw Object.assign(new Error('Gift code invalid or redeemed'),{statusCode:404});db.prepare("UPDATE gift_codes SET status='redeemed',redeemed_by_user_id=?,redeemed_at=? WHERE id=?").run(userId,now(),g.id);return g;}
export function creators(){return getDb().prepare('SELECT * FROM creators ORDER BY name').all();}
export function creatorDashboard(creatorId){const db=getDb();const creator=db.prepare('SELECT * FROM creators WHERE id=?').get(creatorId);if(!creator)return null;return {creator,titles:db.prepare('SELECT * FROM creator_titles WHERE creator_id=?').all(creatorId),revenue:db.prepare('SELECT revenue_type,SUM(gross_cents) gross_cents,SUM(creator_cents) creator_cents,SUM(watchable_cents) watchable_cents FROM creator_revenue_events WHERE creator_id=? GROUP BY revenue_type').all(creatorId),financing:db.prepare('SELECT * FROM creator_financing WHERE creator_id=? ORDER BY created_at DESC').all(creatorId)};}
export function shortForm({limit=50}={}){return getDb().prepare("SELECT * FROM vod_assets WHERE active=1 AND (kind='short' OR json_extract(metadata_json,'$.shortForm')=1) LIMIT ?").all(limit);}
export function franchisePortfolio(){const db=getDb();return db.prepare(`SELECT f.*,COUNT(r.id) rights_count,SUM(CASE WHEN r.status='available' THEN 1 ELSE 0 END) available_rights FROM franchises f LEFT JOIN franchise_rights r ON r.franchise_id=f.id GROUP BY f.id ORDER BY f.name`).all();}
export function rightsExpiring(days=90){return getDb().prepare("SELECT * FROM rights_provenance WHERE expires_at IS NOT NULL AND expires_at<=datetime('now', '+' || ? || ' days') ORDER BY expires_at").all(days);}
export function takeDown(assetType,assetId,reason){const t={id:id('td'),createdAt:now()};getDb().prepare('INSERT INTO takedowns(id,asset_type,asset_id,reason,status,created_at) VALUES(?,?,?,?,?,?)').run(t.id,assetType,assetId,reason,'active',t.createdAt);return t;}
